name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  library-release:
    name: Publish library to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi-lib
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v7
      - run: uv python install
      - run: uv sync --locked --all-extras --package mocklib
      - run: uv build --package mocklib
      - name: Smoke test (wheel)
        run: uv run --isolated --no-project --with dist/*.whl packages/mocklib/tests/smoke_test_lib.py
      - name: Smoke test (source distribution)
        run: uv run --isolated --no-project --with dist/*.tar.gz packages/mocklib/tests/smoke_test_lib.py
      - run: uv publish

  cli-release:
    name: Publish CLI app to PyPI
    runs-on: ubuntu-latest
    needs: library-release
    environment:
      name: pypi-cli
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v7
      - run: uv python install
      - run: uv sync --locked --all-extras --package mockcli
      - run: uv build --no-sources --package mockcli
      - name: Smoke test (wheel)
        run: uv run --isolated --no-project --with dist/*.whl packages/mockcli/tests/smoke_test_cli.py
      - name: Smoke test (source distribution)
        run: uv run --isolated --no-project --with dist/*.tar.gz packages/mockcli/tests/smoke_test_cli.py
      - run: uv publish
