name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  library-release:
    name: Build and publish library
    runs-on: ubuntu-latest
    environment:
      name: pypi-lib
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v7
      - run: uv python install
      - run: uv sync --locked --all-extras --package mocklib
      - run: uv build --package mocklib
      - run: uv publish

  cli-release:
    name: Build and publish cli app
    runs-on: ubuntu-latest
    needs: library-release
    environment:
      name: pypi-cli
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v7
      - run: uv python install
      - run: uv sync --locked --all-extras --package mockcli
      - run: uv build --no-sources --package mockcli
      - run: uv publish
